Algoritmo genz
	definir prueba1, matriz Como Caracter
	definir validar,valLetra como logico
	definir long,i,j,dim,cont Como Entero
	cont=0
	prueba1="ACDDCADBCDABDBBA"
	//prueba1="BCBBABBACBBBBCBB"
    //prueba1="ADDDABBDD"
    //prueba1="CCADDBACCDDDDBDBCCABBAABDBCDCADDABABCDCDDABBBCABBABBDCADCCDABDDACDBBBDBDCCDDCABCAAAACDCDCCACD
	//CDDADAADDACBDBCCDDBCBCBBAAADDAADCAABBBCBCCBCBDBCCBBCBABADAACDBDBADCBBACDADAADABBDBDBDBDCCDDCABCCCCCADBBBB
	//CCDACCBBBDBDAADDBCCBCCBCBDDDDCCBAAACDDBBCAABAADABBBCCCCDCCBBDCDABCDACBCBACDBCCDABDBDCDCADCCBBADDBDCCADCCD
	//CCACCDCDBCDBBADBAADBBCAADDABCAADADAABAACCBABDADADADDBCABDCCBBAADDDCDDCBADBCACCAAADCCDDABDBACBCAAADDBADBDA
	//prueba1="ABAABBCBD"
	//prueba1="CDDACCACCACAAABC"
	//prueba1="ACCDBBADDDCCBACABDCBDCBADBDACBBBBDAABBCCBAACCABDBDCDDABDBDADAAACBBBBCDDDCBBBDDCDABBDDABDBDBBACADCDAAADACDDDACCDCACDDABACDCCCAABDDCCACDADDBCBAACCDBCBCDDDCAACCBAADCBBBCDCBBACBDCCDDADBABCAABBACABDCAACCBDADDCAAACCDBDBBCDDDDDACBCDDADDDDCBADADBDCADDABBCDAACBCCDDDADDADADAACCACDCDDABCCCADABBACDACCAADDBCBCCDADBCCADAAABDDDAABBABCADDCCAADDCDDCDCACBADADACADDAADCBDBCDBDDACDCBCDCCABBDCBACDDACCCDADBCADCACAAABBBCADDDDBCBACDBDAAADDDACCDACBBBADACCCDCACCBACDADBCBBDADACABAACBCCADDCCCCACCCCADBCCDAADCAABBABAADDBDADDABABCCABBCDDACCADAAADBBCCDBADCADCBBDADACCDDBCAAABBBDCAAAACBAADBABBABACDDBBCBDCDCADABABBDADCBADAACDBCBDABADBCBADCACADAABCDDCABACDDBDCBCBDCAAACBDABBCACBACCCBACACDCADBDCDCDDCAACDBDCBACDBBDAABDBBCBAAADBABDBAACAAACDCDAAABABDDDBCACADCBBAADCCDABCCCBBCACCBAABDAADDDCDACDDDBCDCCBABDABACCDCDCDABAABCABBADADCBDDACDDCDDCDACDADADCACBCDABABDDCCDBCCDABACDBDAABDBDDDBADDBACABDCDDBACDDBBDDBBACBCCAACABBDADDBCAACCBCCDADDBCAADDADCCCBAAABABBBBBCABAACADBCBBABACCABCDAABADCCCCDCCADDDCCABBDDDAAADDADACBBBCBDAADACABABBAACCCADADDABDBCADDDCCDBBCCBCDCDBDDDDCACDACDBBBDDBADDACADDADDABCACDCBBADDABBBDCBBDCDAABADDDDDBCACCCCAAACBCBCDBACCCDACCCDBCBDCBADBCDDACCDBDBDBCAAACDDCBAABDBCAADCADDBABABDCBCBCBBBCACBCADDCAAAAAACBBACBBCCACBDCDDDDADCAAACBABDDBDADBAADCBABDDBCDBABDBAADDDBACBBBCCCDBDDBDDAADBBADADDDCBCACBABCDBBABAADABCABCDBACBBBCDBADADDBDCBDABBDDDCDDCCACDCBDCADABAABCDCAACCDDBADBDBCDACAAACBCADCCCBAC"
    //prueba1="CACBCACAC"
    //prueba1="BCAADCCBABCCBABB"

	long=Longitud(prueba1)
	
//		SiNo
//			valLetra=falso
//		FinSi
//	FinPara
	//si valLetra=Verdadero entonces
		
	
	si long=9 o long=16 o long=1369 Entonces
		validar=Verdadero
		dim=raiz(long)
		dimension matriz[dim,dim]
		
		para i=0 Hasta dim-1 Hacer
			para j=0 hasta dim-1 hacer
				matriz[i,j]=Subcadena(prueba1,cont,cont)
			    cont=cont+1
				finpara
		FinPara
      
	SiNo
		validar=falso
		Escribir "La cadena ingresada debe tener 9,16 o 1369 caracteres"
	FinSi
	
    imprimirMatriz(matriz,i,j,dim)
	validarGenZ(matriz,dim)
	
	//finsi
FinAlgoritmo

SubProceso imprimirMatriz(matriz,i,j,dim)
	
	para i=0 Hasta dim-1 Hacer
		para j=0 hasta dim-1 Hacer
			escribir sin saltar matriz[i,j], " " 
		FinPara
		Escribir " "
	FinPara
	
FinSubProceso

SubProceso validarGenZ(matriz,dim)
	definir i,j,cont Como Entero
	definir aux,aux2 como caracter
	definir validacion1,validacion2 Como Logico
	validacion1=Verdadero
	validacion2=verdadero
	
	para i=1 Hasta dim-1 Hacer
		para j=1 Hasta dim-1 Hacer
			si i=j Entonces
				aux=matriz[i,j]
				si matriz[i-1,j-1]<>aux Entonces
					validacion1=falso
				FinSi
		    finsi
		FinPara
	FinPara

	j=dim-1
	
	para i=0 hasta dim-1 hacer
		si matriz[0,dim-1] <> matriz[i,j] Entonces
			validacion2 = Falso
		FinSi
			j=j-1
			
	finpara
	
	si validacion1=Verdadero y validacion2= Verdadero entonces
		Escribir "Contiene Gen Z"
	SiNo
		Escribir "No contiene Gen Z"
	FinSi
	
FinSubProceso
	